(function(g){var window=this;'use strict';var L6d=function(n,q){if(!Number.isFinite(n))return String(n);n=String(n);var M=n.indexOf(".");M===-1&&(M=n.length);var t=n[0]==="-"?"-":"";t&&(n=n.substring(1));return t+(0,g.sTL)("0",Math.max(0,q-M))+n},PjS=function(){return{j:"svg",
K:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},L:[{j:"path",K:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]}},vFd=function(){return{j:"svg",
K:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},L:[{j:"path",K:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]}},lnQ=function(n){typeof n==="number"?(this.date=T4w(n,0,1),se(this,1)):g.Yw(n)?(this.date=T4w(n.getFullYear(),n.getMonth(),n.getDate()),se(this,n.getDate())):(this.date=new Date(g.OF()),n=this.date.getDate(),
this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),se(this,n))},T4w=function(n,q,M){q=new Date(n,q,M);
n>=0&&n<100&&q.setFullYear(q.getFullYear()-1900);return q},se=function(n,q){n.getDate()!=q&&n.date.setUTCHours(n.date.getUTCHours()+(n.getDate()<q?1:-1))},Xk=function(n,q){g.KI.call(this,n,{j:"div",
Y:"ytp-reminder-menu",K:{role:"menu",tabindex:"-1"},L:[{j:"div",Y:"ytp-reminder-menu-contents",L:[{j:"div",Y:"ytp-reminder-menu-items"}]}]},100,!0);this.X=q;this.Z=[];this.menuPopupRenderer=void 0;this.items=this.JE("ytp-reminder-menu-items");this.hide()},U8s=function(n){return(n.menuPopupRenderer&&n.menuPopupRenderer.items||[]).reduce(function(q,M){M&&M.menuServiceItemRenderer&&q.push(M.menuServiceItemRenderer);
return q},[])},jX=function(n){g.w.call(this,{j:"div",
L:[{j:"button",aL:["ytp-offline-slate-button","ytp-button"],L:[{j:"div",Y:"ytp-offline-slate-button-icon",Wb:"{{icon}}"},{j:"div",Y:"ytp-offline-slate-button-text",Wb:"{{text}}"}]}]});this.G=n;this.upcomingEventReminderButtonRenderer=this.toggleButtonRenderer=null;this.W=void 0;this.J=this.X=null;(this.S=this.JE("ytp-offline-slate-button"))&&this.V(this.S,"click",this.C);this.hide()},B4S=function(n,q,M){!n.toggleButtonRenderer&&q&&q.toggleButtonRenderer?n.toggleButtonRenderer=q.toggleButtonRenderer:
q&&q.toggleButtonRenderer||(n.toggleButtonRenderer=null);
!n.upcomingEventReminderButtonRenderer&&M&&g.R(M,ubF)?n.upcomingEventReminderButtonRenderer=g.R(M,ubF):M&&g.R(M,ubF)||(n.upcomingEventReminderButtonRenderer=null);SX(n)},SX=function(n){if(n.toggleButtonRenderer){var q=n.toggleButtonRenderer;
if(q.isToggled){var M=q.toggledText?g.b8(q.toggledText):"";n.update({text:M,icon:D8w(q.toggledIcon)})}else M=q.defaultText?g.b8(q.defaultText):"",n.update({text:M,icon:D8w(q.defaultIcon)});n.show()}else n.upcomingEventReminderButtonRenderer?(q=ATs(n))?(M=q.text?g.b8(q.text):"",n.update({text:M,icon:D8w(q.icon)}),n.show()):n.hide():n.hide()},$8n=function(n,q,M){n.J||(n.J=new g.zq(n.G.T().R2));
var t={context:g.kT(n.J.config_||g.KE())};g.ye()&&(t.context.clientScreenNonce=g.ye());t.params=M;g.JW(n.J,q,t,{timeout:5E3,onSuccess:function(){n.upcomingEventReminderButtonRenderer&&n.W&&(n.upcomingEventReminderButtonRenderer.currentState=n.W,n.W=void 0)},
onError:function(){m8Q(n)},
onTimeout:function(){m8Q(n)}})},m8Q=function(n){n.toggleButtonRenderer?(n.toggleButtonRenderer.isToggled=!n.toggleButtonRenderer.isToggled,SX(n)):n.upcomingEventReminderButtonRenderer&&(n.W=void 0,SX(n))},D8w=function(n){if(!n)return null;
switch(n.iconType){case "NOTIFICATIONS":return PjS();case "NOTIFICATIONS_NONE":return vFd();case "NOTIFICATIONS_ACTIVE":return g.yX();default:return null}},ATs=function(n){if(!n.upcomingEventReminderButtonRenderer)return null;
var q=n.W||n.upcomingEventReminderButtonRenderer.currentState;n=g.S(n.upcomingEventReminderButtonRenderer.states||[]);for(var M=n.next();!M.done;M=n.next())if((M=g.R(M.value,F6O))&&M.state===q&&M.button&&g.R(M.button,g.N_))return g.R(M.button,g.N_);return null},ZqK=function(n){g.w.call(this,{j:"div",
Y:"ytp-offline-slate",L:[{j:"div",Y:"ytp-offline-slate-background"},{j:"div",Y:"ytp-offline-slate-bar",L:[{j:"span",Y:"ytp-offline-slate-icon",L:[{j:"svg",K:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},L:[{j:"path",K:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{j:"circle",K:{cx:"12",cy:"12",r:"3"}}]}]},{j:"span",Y:"ytp-offline-slate-messages",L:[{j:"div",Y:"ytp-offline-slate-main-text",K:{"aria-label":"{{label}}"},Wb:"{{mainText}}"},{j:"div",Y:"ytp-offline-slate-subtitle-text",Wb:"{{subtitleText}}"}]},{j:"span",Y:"ytp-offline-slate-buttons"}]},{j:"button",aL:["ytp-offline-slate-close-button","ytp-button"],L:[g.gW()]},{j:"button",aL:["ytp-offline-slate-open-button","ytp-button"],L:[g.Om()]}]});var q=this;this.api=n;this.X=this.W=null;this.background=this.JE("ytp-offline-slate-background");
this.Z=this.JE("ytp-offline-slate-bar");this.S=new g.zw(function(){g.MN(q.Z,"ytp-offline-slate-bar-fade")},15E3);
this.C=!1;this.J=new g.zw(function(){g.MN(q.element,"ytp-offline-slate-collapsed")},15E3);
g.Z(this,this.J);g.Z(this,this.S);this.countdownTimer=new g.zw(this.eq,1E3,this);this.V(n,"presentingplayerstatechange",this.TO);this.V(n,"livestatedata",this.Cm);this.V(this.JE("ytp-offline-slate-close-button"),"click",function(){g.MN(q.element,"ytp-offline-slate-collapsed")});
this.V(this.JE("ytp-offline-slate-open-button"),"click",function(){g.ts(q.element,"ytp-offline-slate-collapsed")});
this.hide();n=this.getVideoData();n.getPlayerResponse()&&(n=n.getPlayerResponse().playabilityStatus)&&this.Cm(n);n=this.api.getPresentingPlayerType()===8&&!this.getVideoData().GF;var M=this.api.getPresentingPlayerType()===8;g.Yi(this.element,"ytp-offline-slate-premiere-trailer",n);g.Yi(this.element,"ytp-offline-slate-hide-background",M)},anD=function(n,q,M){if(q){var t=q.subtitleText!=null?g.b8(q.subtitleText):"";
M=M?M:q.mainText!=null?g.b8(q.mainText):"";var c,Y,G,k;q=(k=(c=q.mainText)==null?void 0:(Y=c.accessibility)==null?void 0:(G=Y.accessibilityData)==null?void 0:G.label)!=null?k:M;n.update({mainText:M,subtitleText:t,label:q});g.Yi(n.element,"ytp-offline-slate-single-text-line",!t);g.Yi(n.Z,"ytp-offline-slate-bar-hidden",!M&&!t)}},Iv=function(n,q){var M=(0,g.jt)();
this.trigger=n;this.X=q;this.Z=M},Van=function(n){g.Ib.call(this,n);
var q=this;this.N=!1;this.B=0;this.S=!1;this.W=new g.zw(function(){RFd(q)},0);
this.X=this.heartbeatParams=null;this.J=!1;this.C=new g.u9(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.xl=new g.zq(void 0);this.attestationResponse=Promise.resolve(void 0);this.U=Promise.resolve(void 0);this.utcOffsetMinutes=-(new lnQ).getTimezoneOffset();this.Z=new g.f8(this);g.Z(this,this.W);g.Z(this,this.Z);oFs(this);wmT(this);this.Z.V(n,"heartbeatparams",this.yz);this.Z.V(n,"presentingplayerstatechange",this.f$);this.Z.V(n,"videoplayerreset",this.DF);this.Z.V(n,g.CK("heartbeat"),
this.onCueRangeEnter);this.J&&this.X&&zFF(this,void 0,this.X);var M=new g.Ji(fR(this,!0),0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),t=new g.Ji(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});n.y6([M,t]);JTn(this)},JTn=function(n){var q=n.getVideoData();
!q.D("use_rta_for_player")&&q.Z7&&(q=q.botguardData)&&g.eW(q,n.player.T())},Cjw=function(n){var q,M;
return g.u(function(t){if(t.X==1)return g.U(t,g.Bwj(),2);if(!t.W)return n.sequenceNumber>=3?t.return({error:"ATTESTATION_ERROR_VM_INTERNAL_ERROR"}):t.return(void 0);q=n.getVideoData();M={};return t.return(g.uts((M.cpn=q.clientPlaybackNonce,M.encryptedVideoId=q.videoId||"",M),1500))})},oFs=function(n){var q=n.getVideoData();
if(q.Z7)if(q.D("use_rta_for_player"))n.attestationResponse=Cjw(n);else if(q=new g.Rtm(q),g.Nl.isInitialized()||n.sequenceNumber>=3){var M=Promise,t=M.resolve,c=null;if(q.videoData.qH){var Y=g.o8f(q);if(Y){c={};var G={};Y=Y.split("&");Y=g.S(Y);for(var k=Y.next();!k.done;k=Y.next())k=k.value.split("="),k.length===2&&(G[k[0]]=k[1]);G.r1a&&(c.webResponse=G.r1a);G.r1c&&(c.error=rTs[Number(G.r1c)]);c.challenge=q.videoData.qH}}n.attestationResponse=t.call(M,c||void 0)}},x8s=function(n){var q=n.getVideoData();
if(!g.V3(n.getVideoData())||q.cM)return!1;if(q.S){n=q.S.flavor==="playready"&&q.D("html5_innertube_heartbeats_for_playready");var M=q.S.flavor==="widevine"&&q.D("html5_innertube_heartbeats_for_widevine");q=g.N0(q.S)&&q.D("html5_innertube_heartbeats_for_fairplay");return!(n||M||q)}return!0},QyS=function(n){if(x8s(n))return!!n.heartbeatParams;
var q=n.getVideoData();return!g.V3(n.getVideoData())||q.Wk||q.rY?!!q.heartbeatToken:!1},HG=function(n,q){if(!n.W.isActive()&&n.N){var M=n.getVideoData();
if(QyS(n)||M.isLivePlayback){if(q===void 0)if(n.S)if(n.J)q=7500;else{var t;q=((t=n.heartbeatParams)==null?0:t.interval)?n.heartbeatParams.interval*1E3:n.getVideoData().E7||6E4}else q=1E3;n.W.start(q)}}},MZA=function(n,q,M){q.CG&&(M=g.hC(M,{internalipoverride:q.CG}));
var t={cpn:q.clientPlaybackNonce};q.contextParams&&(t.context_params=q.contextParams);q.o8&&(t.kpt=q.o8);M=g.hC(M,t);g.X$(M,{format:"RAW",method:"GET",timeout:3E4,onSuccess:function(c){if(!n.W.isActive()&&LR(n)){n.C.reset();n.sequenceNumber++;c=c.responseText;var Y=pmO(c);if(Y){n.player.Km("onHeartbeat",Y);var G=Y.status==="ok"?Y.stop_heartbeat?2:0:Y.status==="stop"?1:Y.status==="live_stream_offline"?0:-1}else G=(G=c.match(nbn))?G[1]==="0"?0:1:-1;qZQ(n,void 0,Y,c,G)}},
onError:function(c){LR(n)&&PG(n,!0,"net-"+c.status)},
onTimeout:function(){LR(n)&&PG(n,!0,"timeout")},
withCredentials:!0})},RFd=function(n){var q,M;
g.u(function(t){q=n.player.T();M=n.getVideoData();if(!LR(n))return t.return();if(x8s(n))return iCT(n,q,M),t.Fy(0);oFs(n);return g.U(t,tZd(n,q,M),0)})},iCT=function(n,q,M){var t;
if((t=n.heartbeatParams)!=null&&t.url){var c=g.hC(n.heartbeatParams.url,{request_id:g.Ska()});M.IL&&(c=g.hC(c,{vvt:M.IL}),M.mdxEnvironment&&(c=g.hC(c,{mdx_environment:M.mdxEnvironment})));g.BN(q,M.oauthToken).then(function(Y){Y&&(c=g.hC(c,{access_token:Y}));MZA(n,M,c)})}},LR=function(n){var q=n.getVideoData();
return n.player.getPresentingPlayerType()===3||g.C(n.player.getPlayerStateObject(n.getPlayerType()),4)?!1:QyS(n)||q.isLivePlayback?!0:(vG(n),!1)},tZd=function(n,q,M){var t,c,Y,G,k,b,d,N,O,e,E,h,I,L,T,v,B,m,a,x;
return g.u(function(V){if(V.X==1)return t="player/heartbeat",Y={videoId:M.videoId,sequenceNumber:n.sequenceNumber,heartbeatServerData:(c=n.RL)!=null?c:M.heartbeatServerData},n.U=n.attestationResponse,M.Z7?g.U(V,n.U,3):V.Fy(2);V.X!=2&&(Y.attestationResponse=V.W);G=g.Li(M);b=(k=G.client)!=null?k:{};b.utcOffsetMinutes=n.utcOffsetMinutes;Y.context=G;Y.cpn=M.clientPlaybackNonce;if(d=typeof Intl!=="undefined"?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)b.timeZone=d;N={heartbeatChecks:[]};
if(O=M.getPlayerResponse())M.heartbeatToken&&(Y.heartbeatToken=M.heartbeatToken),(e=O.playabilityStatus)&&(E=e.liveStreamability)&&E.liveStreamabilityRenderer&&N.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");M.heartbeatToken&&N.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");g.e$(q)&&(N.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED"),h=cts(n),I={},h!==null&&(I.clientPlayerPositionUtcMillis=h),T=(L=n.player.zk())==null?void 0:g.B0(L),B=((v=T)==null?void 0:v.freePreviewWatchedDuration)||
0,B>0&&(I.freePreviewWatchedDuration={seconds:""+B}),N.unpluggedParams=I);Y.heartbeatRequestParams=N;M.isLivePlayback?(m=cts(n),m!==null&&(Y.playbackState||(Y.playbackState={}),Y.playbackState.playbackPosition={utcTimeMillis:m})):q.D("enable_heartbeat_vod_playback_position")&&(a=YZA(n),a!==null&&(Y.playbackState||(Y.playbackState={}),Y.playbackState.playbackPosition={streamTimeMillis:a}));n.player.publish("heartbeatRequest",Y);x={timeout:3E4,onSuccess:function(bf){if(!n.W.isActive()&&LR(n)){var Ka=
n.getVideoData(),dd=Ka.Z7&&n.U==null,gd;Ka.Z7=!((gd=bf.heartbeatAttestationConfig)==null||!gd.requiresAttestation)||dd;dd=bf.playabilityStatus;gd=JSON.stringify(dd)||"{}";bf.authenticationMismatch&&n.player.Xy("authshear",{});var MR=-1;var lf=bf.playabilityStatus;lf&&(n.player.Km("onHeartbeat",lf),lf.status==="OK"?MR=bf.stopHeartbeat?2:0:lf.status==="UNPLAYABLE"?MR=1:lf.status==="LIVE_STREAM_OFFLINE"&&(MR=0));n.sequenceNumber&&MR===-1||n.C.reset();n.sequenceNumber++;bf.heartbeatServerData&&(n.RL=
bf.heartbeatServerData);Ka.Dw=bf;(lf=bf.playerCueRangeSet)&&g.Ii(Ka,lf);bf.playerCueRanges&&bf.playerCueRanges.length>0&&(Ka.cueRanges=bf.playerCueRanges);var rd,gT;((rd=bf.progressBarConfig)==null?0:rd.progressBarStartPosition)&&((gT=bf.progressBarConfig)==null?0:gT.progressBarEndPosition)&&(Ka.progressBarStartPosition=bf.progressBarConfig.progressBarStartPosition,Ka.progressBarEndPosition=bf.progressBarConfig.progressBarEndPosition);Ka.compositeLiveIngestionOffsetToken=bf.compositeLiveIngestionOffsetToken;
bf.compositeLiveStatusToken!==Ka.compositeLiveStatusToken&&(Ka.compositeLiveStatusToken=bf.compositeLiveStatusToken);Ka.publish("dataupdated");qZQ(n,bf,dd,gd,MR)}},
onError:function(bf){LR(n)&&PG(n,!0,"net-"+bf.status)},
onTimeout:function(){LR(n)&&PG(n,!0,"timeout")}};
g.BN(q,g.O9(M)).then(function(bf){bf&&(x.zw="Bearer "+bf);g.JW(n.xl,t,Y,x)});
g.Sk(V)})},qZQ=function(n,q,M,t,c){c===-1?(M="decode "+g.vn(t,3),PG(n,!1,M)):c===2?(vG(n),n.S=!0):(n.B=0,n.W.stop(),c===1?(n.S=!1,M&&M.errorCode==="PLAYABILITY_ERROR_CODE_EMBARGOED"&&n.player.Ul(!0),c="pe."+(M==null?void 0:M.errorCode)+";ps."+(M==null?void 0:M.status),n.player.gO("heartbeat.stop",2,n.p9(t),c),g.tx("heartbeatActionPlayerHalted",GvS(M)),(q==null?0:q.videoTransitionEndpoint)&&M&&(q=q.videoTransitionEndpoint,(t=g.R(q,g.HO))&&KJn(n,t,M,{itct:q==null?void 0:q.clickTrackingParams}))):(n.S=
!0,t=0,n.J&&M&&(t=zFF(n,q,M),n.player.publish("livestatedata",M)),t?HG(n,t):HG(n)))},zFF=function(n,q,M){var t=M.liveStreamability&&M.liveStreamability.liveStreamabilityRenderer,c=!(!t||!(t.switchStreamsImmediately||t.transitionTiming&&t.transitionTiming==="STREAM_TRANSITION_TIMING_IMMEDIATELY"));
q=kvd(n,q,t);var Y=n.getVideoData(),G=n.player.getPlayerStateObject(n.getPlayerType()),k=G.isPlaying()&&!g.qm(Y)&&!n.player.isAtLiveHead(n.getPlayerType());if(Y.T().Aq()){var b,d=((b=n.player.Q6())==null?void 0:b.Bg())||{};d.status=M.status||"";d.dvr=""+ +k;d["switch"]=""+ +c;d.ended=""+ +!(!t||!t.displayEndscreen);n.player.Xy("heartbeat",d)}b=t&&t.broadcastId;d=n.X&&n.X.liveStreamability&&n.X.liveStreamability.liveStreamabilityRenderer&&n.X.liveStreamability.liveStreamabilityRenderer.broadcastId;
var N=b!==d&&b!=null;N&&n.player.Xy("lbidh",{broadcastId:b},!0);var O=n.player.D("always_cache_redirect_endpoint");if(k&&!c&&!O)return q;var e=t&&t.streamTransitionEndpoint&&g.R(t.streamTransitionEndpoint,g.HO),E=t&&t.transitionTiming;if(E==="STREAM_TRANSITION_TIMING_AT_STREAM_END")n.getVideoData().transitionEndpointAtEndOfStream=e;else if(O&&!e&&n.getVideoData().transitionEndpointAtEndOfStream)n.getVideoData().transitionEndpointAtEndOfStream=void 0;else if(!O&&e&&KJn(n,e,M))return q;if(k&&!c&&O||
O&&e&&(E==="STREAM_TRANSITION_TIMING_IMMEDIATELY"||E==="STREAM_TRANSITION_TIMING_UNSPECIFIED")&&KJn(n,e,M))return q;if(M.status.toUpperCase()==="OK"){if(!g.Q3(Y)||N){var h={video_id:Y.videoId};Y.Ot&&(h.is_live_destination="1");h.disable_watch_next=!0;h.raw_watch_next_response=Y.getWatchNextResponse();h.autonav_state=Y.autonavState;h.oauth_token=Y.oauthToken;h.h_=Y.h_;Y.C&&(h.vss_credentials_token=Y.C,h.vss_credentials_token_type=Y.Ww);Y.IL&&(h.vvt=Y.IL);t=void 0;g.Q3(Y)?N&&(t=new Iv("broadcastIdChanged",
d+","+b),n.Ar("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",M)):(b&&(t=new Iv("formatsReceived",""+b)),n.Ar("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",M));N&&n.player.Xy("lbidr",{broadcastId:b});n.player.loadVideoByPlayerVars(h,void 0,void 0,void 0,t);return q}n.player.fu("heartbeat",n.getPlayerType())}t&&t.displayEndscreen&&(n.offlineSlate?(n=n.offlineSlate,n.C=!0,n.Zn&&n.api.cF()):G.isBuffering()&&
(Y=((h=n.player.Q6())==null?void 0:h.Bg())||{},n.player.Xy("hbse",Y,!0),n.player.cF(!0,"h"),n.player.Km("onLiveMediaEnded",M)));return q},kvd=function(n,q,M){return n.player.D("web_player_use_heartbeat_poll_delay_ms")&&(n=Number(q==null?void 0:q.pollDelayMs))?n:(M=Number(M==null?void 0:M.pollDelayMs))?M:0},PG=function(n,q,M){if(!n.W.isActive()){n.W.stop();
n.B++;var t=q?"heartbeat.net":"heartbeat.servererror";var c=n.getVideoData();if(c.g1||q&&!g.V3(n.getVideoData())&&!QyS(n)&&c.isLivePlayback)c=!1;else{var Y,G;((G=n.heartbeatParams)==null?0:G.retries)?Y=n.heartbeatParams.retries:Y=c.bQ||5;c=n.B>=Y}c?(g.tx("heartbeatActionPlayerHalted",q?{enforcedPolicyToHaltOnNetworkFailure:!0}:GvS()),(q=n.getVideoData())&&q.isLivePlayback?n.player.gO(t,1,"Pemutaran video mengalami gangguan. Coba lagi.",M):n.player.gO(t,1,"Maaf, terjadi error saat memberikan lisensi untuk video ini.",
M)):(HG(n,n.C.getValue()),g.BL(n.C))}},GvS=function(n){var q={enforcedPolicyToHaltOnNetworkFailure:!1};
n&&(q.serializedServerContext=n.additionalLoggingData);return q},vG=function(n){n.B=0;
n.W.stop();n.S=!1;n.sequenceNumber=0},wmT=function(n){var q=n.getVideoData(),M=n.player.T();
if(q.isLivePlayback)if(g.Lx(M.S)){n.J=!0;n.N=!0;if(!g.hi(M)||g.e$(M))n.offlineSlate=new ZqK(n.player),g.Z(n,n.offlineSlate),g.qW(n.player,n.offlineSlate.element,4);(q=q.getPlayerResponse())&&q.playabilityStatus&&(n.X=q.playabilityStatus);var t;((t=n.X)==null?void 0:t.status)!=="UNPLAYABLE"&&(n.X?(t=kvd(n,void 0,n.X.liveStreamability&&n.X.liveStreamability.liveStreamabilityRenderer))?HG(n,t):HG(n,7500):HG(n,fR(n,!0)))}else n.player.gO("html5.unsupportedlive",2,"HTML5_NO_AVAILABLE_FORMATS_FALLBACK",
"nolive.1");else g.SS(q.wJ,"heartbeat")&&n.player.fu("heartbeat",n.getPlayerType())},KJn=function(n,q,M,t){var c=q&&q.videoId;
return c?(n.player.u4(c,Object.assign({},{autonav:"1"},t||{}),void 0,!0,!0,q,g.O9(n.getVideoData())),n.Ar("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",M),!0):!1},cts=function(n){return(n=n.player.getProgressState(n.getPlayerType()).ingestionTime)&&isFinite(n)?""+Math.floor(n*1E3):null},YZA=function(n){return(n=n.player.getCurrentTime(n.getPlayerType()))&&isFinite(n)?""+Math.floor(n*1E3):null},fR=function(n,q){q=q===void 0?!1:q;
n=n.getVideoData();return n.D("html5_use_server_init_heartbeat_delay")?isNaN(n.E7)?15E3:n.E7:q?1E3:2E3},pmO=function(n){try{var q=JSON.parse(n);
return q!=null?q:void 0}catch(M){}},bCD={ERAS:["BC",
"AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y",
"MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5};
bCD={ERAS:["SM","M"],ERANAMES:["Sebelum Masehi","Masehi"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"Januari Februari Maret April Mei Juni Juli Agustus September Oktober November Desember".split(" "),STANDALONEMONTHS:"Januari Februari Maret April Mei Juni Juli Agustus September Oktober November Desember".split(" "),SHORTMONTHS:"Jan Feb Mar Apr Mei Jun Jul Agu Sep Okt Nov Des".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr Mei Jun Jul Agu Sep Okt Nov Des".split(" "),
WEEKDAYS:"Minggu Senin Selasa Rabu Kamis Jumat Sabtu".split(" "),STANDALONEWEEKDAYS:"Minggu Senin Selasa Rabu Kamis Jumat Sabtu".split(" "),SHORTWEEKDAYS:"Min Sen Sel Rab Kam Jum Sab".split(" "),STANDALONESHORTWEEKDAYS:"Min Sen Sel Rab Kam Jum Sab".split(" "),NARROWWEEKDAYS:"MSSRKJS".split(""),STANDALONENARROWWEEKDAYS:"MSSRKJS".split(""),SHORTQUARTERS:["K1","K2","K3","K4"],QUARTERS:["Kuartal ke-1","Kuartal ke-2","Kuartal ke-3","Kuartal ke-4"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, dd MMMM y","d MMMM y",
"d MMM y","dd/MM/yy"],TIMEFORMATS:["HH.mm.ss zzzz","HH.mm.ss z","HH.mm.ss","HH.mm"],DATETIMEFORMATS:["{1} 'pukul' {0}","{1} 'pukul' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5};
var rTs=["ATTESTATION_ERROR_UNKNOWN","ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"],dOs={300:"STREAMING_DEVICES_QUOTA_PER_24H_EXCEEDED",301:"ALREADY_PINNED_ON_A_DEVICE",303:"STOPPED_BY_ANOTHER_PLAYBACK",304:"TOO_MANY_STREAMS_PER_USER",305:"TOO_MANY_STREAMS_PER_ENTITLEMENT",400:"VIDEO_NOT_FOUND",401:"GEO_FAILURE",402:"STREAMING_NOT_ALLOWED",403:"UNSUPPORTED_DEVICE",405:"VIDEO_FORBIDDEN",500:"PURCHASE_NOT_FOUND",
501:"RENTAL_EXPIRED",502:"PURCHASE_REFUNDED",5E3:"BAD_REQUEST",5001:"CGI_PARAMS_MISSING",5002:"CGI_PARAMS_MALFORMED",5100:"AUTHENTICATION_MISSING",5101:"AUTHENTICATION_MALFORMED",5102:"AUTHENTICATION_EXPIRED",5200:"CAST_TOKEN_MALFORMED",5201:"CAST_TOKEN_EXPIRED",5202:"CAST_TOKEN_FAILED",5203:"CAST_SESSION_VIDEO_MISMATCHED",5204:"CAST_SESSION_DEVICE_MISMATCHED",6E3:"INVALID_DRM_MESSAGE",7E3:"SERVER_ERROR",8E3:"RETRYABLE_ERROR"};g.W=lnQ.prototype;g.W.TC=bCD.FIRSTDAYOFWEEK;g.W.UK=bCD.FIRSTWEEKCUTOFFDAY;
g.W.clone=function(){var n=new lnQ(this.date);n.TC=this.TC;n.UK=this.UK;return n};
g.W.getFullYear=function(){return this.date.getFullYear()};
g.W.getYear=function(){return this.getFullYear()};
g.W.getMonth=function(){return this.date.getMonth()};
g.W.getDate=function(){return this.date.getDate()};
g.W.getTime=function(){return this.date.getTime()};
g.W.getDay=function(){return this.date.getDay()};
g.W.getUTCFullYear=function(){return this.date.getUTCFullYear()};
g.W.getUTCMonth=function(){return this.date.getUTCMonth()};
g.W.getUTCDate=function(){return this.date.getUTCDate()};
g.W.getUTCDay=function(){return this.date.getDay()};
g.W.getUTCHours=function(){return this.date.getUTCHours()};
g.W.getUTCMinutes=function(){return this.date.getUTCMinutes()};
g.W.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};
g.W.set=function(n){this.date=new Date(n.getFullYear(),n.getMonth(),n.getDate())};
g.W.setFullYear=function(n){this.date.setFullYear(n)};
g.W.setYear=function(n){this.setFullYear(n)};
g.W.setMonth=function(n){this.date.setMonth(n)};
g.W.setDate=function(n){this.date.setDate(n)};
g.W.setTime=function(n){this.date.setTime(n)};
g.W.setUTCFullYear=function(n){this.date.setUTCFullYear(n)};
g.W.setUTCMonth=function(n){this.date.setUTCMonth(n)};
g.W.setUTCDate=function(n){this.date.setUTCDate(n)};
g.W.add=function(n){if(n.years||n.months){var q=this.getMonth()+n.months+n.years*12,M=this.getYear()+Math.floor(q/12);q%=12;q<0&&(q+=12);a:{switch(q){case 1:var t=M%4!=0||M%100==0&&M%400!=0?28:29;break a;case 5:case 8:case 10:case 3:t=30;break a}t=31}t=Math.min(t,this.getDate());this.setDate(1);this.setFullYear(M);this.setMonth(q);this.setDate(t)}n.days&&(M=this.getYear(),q=M>=0&&M<=99?-1900:0,n=new Date((new Date(M,this.getMonth(),this.getDate(),12)).getTime()+n.days*864E5),this.setDate(1),this.setFullYear(n.getFullYear()+
q),this.setMonth(n.getMonth()),this.setDate(n.getDate()),se(this,n.getDate()))};
g.W.equals=function(n){return!(!n||this.getYear()!=n.getYear()||this.getMonth()!=n.getMonth()||this.getDate()!=n.getDate())};
g.W.toString=function(){var n=this.getFullYear(),q=n<0?"-":n>=1E4?"+":"";return[q+L6d(Math.abs(n),q?6:4),L6d(this.getMonth()+1,2),L6d(this.getDate(),2)].join("")+""};
g.W.valueOf=function(){return this.date.valueOf()};var NlO=new g.Xa("addUpcomingEventReminderEndpoint");var OCd=new g.Xa("removeUpcomingEventReminderEndpoint");var gbS=new g.Xa("updateUpcomingEventReminderButtonStateCommand");var ubF=new g.Xa("upcomingEventReminderButtonRenderer"),F6O=new g.Xa("upcomingEventReminderButtonStateRenderer");g.y(Xk,g.KI);
Xk.prototype.updateMenuItems=function(){var n=this,q=U8s(this),M=0;M=0;for(var t={};M<q.length;t={gW:void 0},M++){var c=this.Z[M];c||(c=new g.w({j:"div",Y:"ytp-reminder-menu-item",K:{role:"menuitem",tabindex:"0"},L:[{j:"div",Y:"ytp-reminder-menu-item-icon",Wb:"{{icon}}"},{j:"div",Y:"ytp-reminder-menu-item-label",Wb:"{{text}}"}]}),t.gW=M,c.listen("click",function(G){return function(){var k=G.gW;n.lG();k=U8s(n)[k];n.publish("reminderMenuItemClicked",k.serviceEndpoint||k.command)}}(t)),c.dJ(this.items),
this.Z[M]=c);
var Y=q[M];t=null;switch(Y.icon&&Y.icon.iconType){case "NOTIFICATIONS":t=PjS();break;case "NOTIFICATIONS_NONE":t=vFd();break;case "NOTIFICATIONS_ACTIVE":t=g.yX()}Y=Y.text?g.b8(Y.text):"";c.update({icon:t,text:Y})}for(;M<this.Z.length;)this.Z.pop().dispose();M===0?this.lG():this.Hn(this.X)};
Xk.prototype.hide=function(){this.X&&this.X.removeAttribute("aria-haspopup");g.KI.prototype.hide.call(this)};
Xk.prototype.show=function(){this.X&&this.X.setAttribute("aria-haspopup","true");g.KI.prototype.show.call(this)};
Xk.prototype.ut=function(){g.tg(this.Z);g.KI.prototype.ut.call(this)};g.y(jX,g.w);
jX.prototype.C=function(){if(this.toggleButtonRenderer){var n=this.toggleButtonRenderer;n.isToggled?this.Z(n.toggledServiceEndpoint):this.Z(n.defaultServiceEndpoint);n.isToggled=!n.isToggled;SX(this)}else if(this.upcomingEventReminderButtonRenderer)if(this.X&&this.X.Zn)this.X.lG();else{var q=ATs(this);q&&this.Z(q.serviceEndpoint||q.command);q=((n=g.R(q==null?void 0:q.command,g.Ov))==null?void 0:n.commands)||[];a:{n=g.S(q);for(var M=n.next();!M.done;M=n.next()){var t=q=void 0;if(M=(q=g.R(M.value,g.lxs))==
null?void 0:(t=q.popup)==null?void 0:t.menuPopupRenderer){n=M;break a}}n=void 0}this.X||(this.X=new Xk(this.G,this.S),this.X.dJ(this.element),g.Z(this,this.X),this.X.subscribe("reminderMenuItemClicked",this.Z,this));q=this.X;q.menuPopupRenderer=n;q.updateMenuItems()}};
jX.prototype.Z=function(n){var q=g.R(n,NlO),M=g.R(n,OCd);if(n&&(q||M)){if(q){var t=q;var c="notification/add_upcoming_event_reminder"}else M&&(t=M,c="notification/remove_upcoming_event_reminder");if(c&&t&&t.params)for($8n(this,c,t.params),n=g.S(t.commands||[]),q=n.next();!q.done;q=n.next())if((q=q.value)&&g.R(q,gbS)){this.W=g.R(q,gbS).state;SX(this);break}}};g.y(ZqK,g.w);g.W=ZqK.prototype;g.W.getPlayerType=function(){if(this.api.getPresentingPlayerType()===8)return 1};
g.W.getVideoData=function(){return this.api.getVideoData(this.getPlayerType())};
g.W.Cm=function(n){var q,M,t=n==null?void 0:(q=n.liveStreamability)==null?void 0:(M=q.liveStreamabilityRenderer)==null?void 0:M.offlineSlate;if(t){this.W=n;q=t.liveStreamOfflineSlateRenderer;q.canShowCountdown?this.eq():anD(this,q);var c,Y,G,k;if(M=n==null?void 0:(c=n.liveStreamability)==null?void 0:(Y=c.liveStreamabilityRenderer)==null?void 0:(G=Y.offlineSlate)==null?void 0:(k=G.liveStreamOfflineSlateRenderer)==null?void 0:k.thumbnail){c=0;Y=null;G=M.thumbnails;for(k=0;k<G.length;k++)G[k].width>
c&&(c=G[k].width||0,Y=G[k].url);Y&&(this.background.style.backgroundImage="url("+Y+")")}else this.background.style.backgroundImage="";q.actionButtons||q.reminderButton?(this.X||(this.X=new jX(this.api),this.X.dJ(this.JE("ytp-offline-slate-buttons")),g.Z(this,this.X)),B4S(this.X,q.actionButtons&&q.actionButtons[0],q.reminderButton)):this.X&&B4S(this.X,null,null);this.W=n}else this.W=null;this.TO()};
g.W.TO=function(n){if(this.api.getPresentingPlayerType()===8)var q=!0;else{var M=this.api.getPlayerStateObject(),t=this.getVideoData();q=t.isLivePlayback&&(M.isBuffering()||g.C(M,2)||g.C(M,64));var c=t.autonavState===2&&g.C(M,2);M=M.isPlaying()&&!g.qm(t)&&!this.api.isAtLiveHead(void 0,!0);q=q&&!M&&!c}q&&this.W?this.Zn?(n==null?0:g.dU(n,2))&&!this.getVideoData().GF&&(g.ts(this.element,"ytp-offline-slate-collapsed"),this.J.stop(),g.ts(this.Z,"ytp-offline-slate-bar-fade"),this.S.start()):(this.show(),
this.J.start(),this.api.publish("offlineslatestatechange"),this.C&&this.api.cF()):this.Zn&&(this.hide(),this.api.publish("offlineslatestatechange"))};
g.W.eq=function(){var n,q,M,t,c=(n=this.W)==null?void 0:(q=n.liveStreamability)==null?void 0:(M=q.liveStreamabilityRenderer)==null?void 0:(t=M.offlineSlate)==null?void 0:t.liveStreamOfflineSlateRenderer;c&&(n=Math.floor(g.OF()/1E3),q=c.canShowCountdown&&Number(c.scheduledStartTime),!q||q<=n?(anD(this,c),this.countdownTimer.stop()):(anD(this,c,g.XB(q-n)),g.Jd(this.countdownTimer)))};
g.W.ut=function(){this.countdownTimer.dispose();this.countdownTimer=null;g.w.prototype.ut.call(this)};Iv.prototype.W=function(n){return this.trigger&&n.trigger?this.trigger===n.trigger&&this.X===n.X:!1};
Iv.prototype.isExpired=function(){return(0,g.jt)()-this.Z>6E4};
Iv.prototype.toString=function(){return"heartbeat:"+this.trigger+":"+this.X};g.y(Van,g.Ib);g.W=Van.prototype;g.W.ut=function(){vG(this);this.player.sT("heartbeat");g.Ib.prototype.ut.call(this)};
g.W.onCueRangeEnter=function(){this.N=!0;HG(this,fR(this))};
g.W.yz=function(n){this.heartbeatParams=n;HG(this,fR(this))};
g.W.f$=function(n){var q;this.player.getPresentingPlayerType()!==8&&((q=this.X)==null?void 0:q.status)!=="UNPLAYABLE"&&(g.C(n.state,2)||g.C(n.state,64)?(vG(this),this.J&&(this.N=!0,HG(this,fR(this,!0)))):(g.C(n.state,1)||g.C(n.state,8))&&HG(this,fR(this)))};
g.W.DF=function(){this.player.getPresentingPlayerType()!==3&&HG(this,fR(this))};
g.W.getPlayerType=function(){if(this.player.getPresentingPlayerType()===8)return 1};
g.W.getVideoData=function(){return this.player.getVideoData(this.getPlayerType())};
g.W.b1=function(n){switch(n){case 4:case 3:return!1}return!0};
g.W.Ar=function(n,q,M){n={trigger:n,reason:q};M&&(n.serializedServerContext=M.additionalLoggingData);g.tx("heartbeatActionPlayerTransitioned",n)};
g.W.p9=function(n){var q="LICENSE",M=pmO(n);if(M)return M.reason||g.zK[q]||"";if(n=n.match(nbn))if(n=Number(n[1]))q=(q=dOs[n.toString()])?q:"LICENSE";return g.zK[q]||""};
g.W.a7=function(){return!!this.offlineSlate&&this.offlineSlate.Zn};
var nbn=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.SC("heartbeat",Van);})(_yt_player);
